# fly.toml app configuration file generated for weekbot on 2025-01-08T20:01:05-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'weekbot'
primary_region = 'ewr'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  entrypoint = ['litefs', 'mount', '--', './main']
  auto_rollback = true

[build]
  dockerfile = 'weekbot-go/Dockerfile'

[env]
  PRIMARY_REGION = 'ewr'

[[mounts]]
  source = 'litefs'
  destination = '/var/lib/litefs'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20
